# Data quality assessment

## Overview

### Objective
Assess data quality of all datasets - Stocks data, Benchmark data and Portfolio holdings, before performing any analytics.

### Datasets
- stock_data.csv
- benchmark_data.csv
- portfolio_holdings.csv

## Loading datasets

In [46]:
import pandas as pd

stocks_df = pd.read_csv("../data/raw/stock_data.csv", sep=",")
benchmark_df = pd.read_csv("../data/raw/benchmark_data.csv", sep=",")
portfolio_df = pd.read_csv("../data/raw/portfolio_holdings.csv", sep=",")

## Dataset preview

In [47]:
print("=" * 60)
print("Stocks")
display(stocks_df.head(5))
print("=" * 60)
print("Benchmark")
display(benchmark_df.head(5))
print("=" * 60)
print("Portfolio holdings")
display(portfolio_df.head(5))
print("=" * 60)

============================================================
Stocks

         Date Ticker       Open       High        Low      Close     Volume
0  2020-01-02   AAPL  71.344062  72.394093  71.091191  72.333885  135480400
1  2020-01-03   AAPL  71.563205  72.389257  71.406666  71.630638  146322800
2  2020-01-06   AAPL  70.754021  72.239950  70.503554  72.201416  118387200
3  2020-01-07   AAPL  72.211041  72.466322  71.642681  71.861839  108872000
4  2020-01-08   AAPL  71.565621  73.318877  71.565621  73.017838  132079200

============================================================
Benchmark

         Date         Open         High          Low        Close      Volume
0  2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3459930000
1  2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3484700000
2  2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3702460000
3  2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3435910000
4  2020-01-08  3238.590088  3267.070068  3236.669922  3253.050049  3726840000

============================================================
Portfolio holdings

  Ticker  Shares  Purchase_Price Purchase_Date
0   AAPL      50             180    2023-05-01
1   MSFT      30             320    2023-06-15
2   NVDA      20             450    2024-01-10
3    JPM      25             180    2023-08-01
4    BAC      40              32    2023-09-15

============================================================

## Dataset Overview

### Shape

In [48]:
print("=" * 60)
print("Rows and Columns")
print("=" * 60)
print("Stocks =", stocks_df.shape)
print("=" * 60)
print("Benchmark =", benchmark_df.shape)
print("=" * 60)
print("Portfolio holdings =", portfolio_df.shape)
print("=" * 60)

============================================================
Rows and Columns
============================================================
Stocks = (10064, 7)
============================================================
Benchmark = (1258, 6)
============================================================
Portfolio holdings = (8, 4)
============================================================

### Column names

In [49]:
print("=" * 60)
print("Stocks columns")
print(stocks_df.columns.to_list())
print("=" * 60)
print("Benchmark columns")
print(benchmark_df.columns.to_list())
print("=" * 60)
print("Portfolio holdings columns")
print(portfolio_df.columns.to_list())
print("=" * 60)

============================================================
Stocks columns
['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume']
============================================================
Benchmark columns
['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
============================================================
Portfolio holdings columns
['Ticker', 'Shares', 'Purchase_Price', 'Purchase_Date']
============================================================

### Info

In [50]:
print("=" * 60)
print("Stocks info")
stocks_df.info()
print("=" * 60)
print("Benchmark info")
benchmark_df.info()
print("=" * 60)
print("Portfolio info")
portfolio_df.info()
print("=" * 60)

============================================================
Stocks info
<class 'pandas.DataFrame'>
RangeIndex: 10064 entries, 0 to 10063
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    10064 non-null  str
 1   Ticker  10064 non-null  str
 2   Open    10064 non-null  float64
 3   High    10064 non-null  float64
 4   Low     10064 non-null  float64
 5   Close   10064 non-null  float64
 6   Volume  10064 non-null  int64
dtypes: float64(4), int64(1), str(2)
memory usage: 550.5 KB
============================================================
Benchmark info
<class 'pandas.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1258 non-null   str
 1   Open    1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Close   1258 non-null   float64
 5   Volume  1258 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 59.1 KB
============================================================
Portfolio info
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Ticker          8 non-null      str
 1   Shares          8 non-null      int64
 2   Purchase_Price  8 non-null      int64
 3   Purchase_Date   8 non-null      str
dtypes: int64(2), str(2)
memory usage: 388.0 bytes
============================================================

**Observation:** All necessary columns are present in their required data type, except dates. Dates are in string format; need to be converted into datatime.

## Missing value analysis

### Missing values in Stocks

In [51]:
stocks_df.isnull().sum()

Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

### Missing values in Benchmark

In [52]:
benchmark_df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

### Missing values in Portfolio Holdings

In [53]:
portfolio_df.isnull().sum()

Ticker            0
Shares            0
Purchase_Price    0
Purchase_Date     0
dtype: int64

**Conclusion:** No missing values found accross all datasets.

## Duplicate Analysis

### Duplicates in Stocks

In [54]:
stocks_df.duplicated().sum()

np.int64(0)

In [55]:
stocks_df.duplicated(subset=['Date', 'Ticker']).sum()

np.int64(0)

### Duplicates in Benchmark

In [56]:
benchmark_df.duplicated().sum()

np.int64(0)

### Duplicates in Portfolio Holdings

In [57]:
portfolio_df.duplicated().sum()

np.int64(0)

**Observation:** No duplicate samples were found.

## Date Validation

### Min and Max dates

In [58]:
print("Min date =", stocks_df["Date"].min())
print("Max date =", stocks_df["Date"].max())

Min date = 2020-01-02
Max date = 2024-12-31

In [59]:
print(stocks_df["Date"].dtype)
print(benchmark_df["Date"].dtype)
print(portfolio_df["Purchase_Date"].dtype)

str
str
str

## Numerical Validation in Stocks

### Negative prices

In [60]:
print("No. of negative Open prices =", (stocks_df["Open"] <= 0).sum())
print("No. of negative High prices =", (stocks_df["High"] <= 0).sum())
print("No. of negative Low prices =", (stocks_df["Low"] <= 0).sum())
print("No. of negative Close prices =", (stocks_df["Close"] <= 0).sum())

No. of negative Open prices = 0
No. of negative High prices = 0
No. of negative Low prices = 0
No. of negative Close prices = 0

**Observation:** No invalid price amounts present.

### Negative volume

In [61]:
print("No. of negative Volumes =", (stocks_df["Volume"] <= 0).sum())

No. of negative Volumes = 0

**Observation:** No invalid volume amounts present.

### High < Low

In [62]:
print((stocks_df["High"] < stocks_df["Low"]).sum())

0

## Portfolio holdings validation

### Invalid shares

In [63]:
(portfolio_df["Shares"] <= 0).sum()

np.int64(0)

### Portfolio Tickers present in Stocks

In [64]:
set(portfolio_df["Ticker"]).difference(set(stocks_df["Ticker"]))

set()

In [65]:
def all_tickers_present() -> bool:
    for ticker in portfolio_df["Ticker"].to_list():
        if (ticker not in stocks_df["Ticker"].to_list()):
            return False
    return True
all_tickers_present()

True

## Assessment Summary Report

| Check | Status | Notes |
| --- | --- | --- |
| Missing Value | Pass | No missing values found |
| Duplicates | Pass | No duplicates found |
| Schema Validation | Warning | Dates are in string format; need to be converted into datetime |
| Portfolio data integrity | Pass | No anomalies found |
| Numerical Validation | Pass | All values are in correct format and range |


_Datasets are suitable for futher analytics and dashboard development._